controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # scaled_joint_trajectory_controller:
    #   type: ur_controllers/ScaledJointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    cartesian_compliance_controller:
      type: cartesian_compliance_controller/CartesianComplianceController

    cartesian_force_controller:
      type: cartesian_force_controller/CartesianForceController

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# scaled_joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     state_publish_rate: 100.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     constraints:
#       stopped_velocity_tolerance: 0.2
#       goal_time: 0.0
#       shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
#       shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
#       elbow_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# FIXME: 需要修改，未config成功
force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: ft_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tool0
    # topic_name: wrench
    topic_name: /ft_sensor_wrench

cartesian_compliance_controller:
  ros__parameters:

    end_effector_link: "tool0"
    robot_base_link: "base"
    ft_sensor_ref_link: "tool0"
    compliance_ref_link: "tool0"

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position
        #- velocity

    stiffness:  # w.r.t. compliance_ref_link coordinates
        trans_x: 300.0  # default = 500
        trans_y: 300.0
        trans_z: 300.0
        rot_x: 15.0     # default = 20
        rot_y: 15.0
        rot_z: 15.0

    solver:
        error_scale: 0.5
        iterations: 1
        publish_state_feedback: True

    # For all controllers, these gains are w.r.t. the robot_base_link coordinates.
    pd_gains:
        # No.5 缓解"阻碍感"
        # [good] 相对轻松
        trans_x: {p: 0.1, d: 0.005}
        trans_y: {p: 0.1, d: 0.005}
        trans_z: {p: 0.1, d: 0.005}
        rot_x: {p: 1.5, d: 0.05}
        rot_y: {p: 1.5, d: 0.05}
        rot_z: {p: 1.5, d: 0.05}

cartesian_force_controller:
  ros__parameters:
    force_deadzone: 1.0           # 力死区阈值(N)   default = 1.0
    torque_deadzone: 0.05         # 力矩死区阈值(Nm) default = 0.05
    calibration_samples: 100      # 调零采样数量     default = 100
    auto_calibration_interval: 90.0  # 自动调零间隔(秒) default = 300.0
    # auto_calibration_interval: 3600.0  # 为了便于realsense采样

    filter_coefficient: 0.05  # 滤波系数(0-1)
                              # 较小的值会产生更平滑的输出但响应更慢
                              # 较大的值响应更快但可能保留更多噪声
    # See the cartesian_compliance_controller
    end_effector_link: "tool0"
    robot_base_link: "base"
    ft_sensor_ref_link: "tool0"
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    # See the cartesian_compliance_controller
    command_interfaces:
      - position
        #- velocity

    solver:
        error_scale: 0.5
        publish_state_feedback: True

    pd_gains:
        # No.5 提高 P,尝试缓解"阻碍感"
        # [good]
        trans_x: {p: 0.08, d: 0.01}
        trans_y: {p: 0.08, d: 0.01}
        trans_z: {p: 0.08, d: 0.01}
        rot_x: {p: 0.8, d: 0.4}
        rot_y: {p: 0.8, d: 0.4}
        rot_z: {p: 0.8, d: 0.4}

cartesian_motion_controller:
  ros__parameters:

    # See the cartesian_compliance_controller
    end_effector_link: "tool0"
    robot_base_link: "base"
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    # See the cartesian_compliance_controller
    command_interfaces:
      - position
        #- velocity

    solver:
        error_scale: 1.0
        iterations: 10
        publish_state_feedback: True

    pd_gains:
        trans_x: {p: 1.0}
        trans_y: {p: 1.0}
        trans_z: {p: 1.0}
        rot_x: {p: 0.5}
        rot_y: {p: 0.5}
        rot_z: {p: 0.5}

motion_control_handle:
  ros__parameters:
    end_effector_link: "tool0"
    robot_base_link: "base"
    ft_sensor_ref_link: "tool0"
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
